### ISSUE TITLE
Pratts Bottom, UK missing

### ISSUE THREAD

**Issue by somnolentsurfer** [vicchi/maps.geotastic.org#13]
Pratts Bottom, near Orpington, UK, should be on here. This is a Google Maps link:

https://maps.google.co.uk/maps?f=q&source=s_q&hl=en&geocode=&q=Pratts+Bottom&aq=0&oq=pratts&sll=52.8382,-2.327815&sspn=8.339986,19.753418&vpsrc=6&ie=UTF8&hq=&hnear=Pratt's+Bottom,+Greater+London,+United+Kingdom&ll=51.340961,0.114198&spn=0.016836,0.038581&t=m&z=15&iwloc=A

**Comment by vicchi** [comment]
Added in commit 7976b8df05b105314784a1eeb12b130742ffff3b
