### ISSUE TITLE
Another one

### ISSUE THREAD

**Issue by stevage** [vicchi/maps.geotastic.org#16]
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [147.90389,-37.68351]
},
"properties": {
"label": "Spanker Knob, Victoria, Australia",
"detail": "Spanker Knob, Victoria, Australia"
}
},

**Comment by vicchi** [comment]
See commit 780e08c47744f67d8f50c612b6f3fe36274d429d, See also: http://maps.geotastic.org/rude/index.php?id=194
