### ISSUE TITLE
Adding 'Moron' in Venezuela.

### ISSUE THREAD

**Issue by n0bi** [vicchi/maps.geotastic.org#25]
Just off the coast, near the Puerto Cabello port.

http://en.wikipedia.org/wiki/Mor%C3%B3n,_Venezuela

![print 2014-07-11 at 09 36 25 a m](https://cloud.githubusercontent.com/assets/8135866/3553522/9a7b0e48-0904-11e4-97d4-f20d40099b29.png)

**Comment by vicchi** [comment]
This issue was moved to vicchi/vaguely-rude-places#27
