### ISSUE TITLE
Big Bone Lick State Park on Beaver Rd.

### ISSUE THREAD

**Issue by goldicecream** [vicchi/maps.geotastic.org#26]
...Just thought that maybe it should be added.

Big Bone Lick State Park
3380 Beaver Rd
Union, KY 41091

Also, maybe Dry Ridge, KY.  And Ballplay, TN.

...I've driven from Michigan to Florida way too many times...

**Comment by vicchi** [comment]
This issue was moved to vicchi/vaguely-rude-places#26
