### ISSUE TITLE
others

### ISSUE THREAD

**Issue by oakvilleon** [vicchi/maps.geotastic.org#27]
Blow Me Down, Newfoundland and Labrador, Canada
Come By Chance, Newfoundland and Labrador, Canada
Crapaud,  Prince Edward Island, Canada
Wood Point, New Brunswick, Canada
Bummers Roost, Ontario, Canada
Climax, Saskatchewan, Canada
Smuts, Saskatchewan, Canada
Sucker River, Saskatchewan, Canada
Tramping Lake, Saskatchewan, Canada
Nogap, Alberta , Canada
Bliss Landing, British Columbia, Canada
Spuzzum, British Columbia, Canada
Squamish, British Columbia, Canada
Stoner, British Columbia, Canada
Ta ta Creek , British Columbia, Canada
Snag, Yukon, Canada

**Comment by jaredmcateer** [comment]
Dildo, Newfoundland and Labrador, Canada

**Comment by vicchi** [comment]
This issue was moved to vicchi/vaguely-rude-places#25
